name: Build Project (Windows, Release)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: dotnet build src/Terminaux.TermInfo.sln --configuration Release
    - name: Testing
      run: dotnet test src/Terminaux.TermInfo.sln --no-build --configuration Release
        
