name: Build Project (Linux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: dotnet build src/Terminaux.TermInfo.sln --configuration Debug
    - name: Testing
      run: dotnet test src/Terminaux.TermInfo.sln --configuration Debug
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: tr-build
        path: "src/Terminaux.TermInfo/bin/Debug/"
        
